### PR TITLE
add Turkish translation

### PR DESCRIPTION
**Pull request by J3ekir**
I don't know where you guys take the flags from.

### CODE REVIEW

**Comment by drHyperion451** [comment]
Hello, the flags are inside ./assets/icons/ folder. Update a flag similar to the other flags in .svg and put it inside the folder. After that, add the flag inside index.html in this line: https://github.com/drHyperion451/does-uBO-bypass-yt/blob/f7bb77d628cd9c2bd64ef03132f27c5c30a2613e/index.html#L29 

Look how other langs do it and it should work fine.
I'll merge it after that. Thanks.

**Comment by J3ekir** [comment]
Didn't realize they are not in the same form. I though you edit them.
Considering the situation and with your permission I'm making all same form. Right now I'll only do Turkish flag so you can see and might want to change the values.

### Steps
- Find a rectangular flag (sorry Nepal) from Wikimedia (If it's not on there, elsewhere) to be edited in Adobe Illustrator. 
- Object > Envelope Distort > Make with Warp... > Style: Flag, Horizontal, Bend: -10%, rest is 0%.
- Object > Transform > Rotate... > Angle: 10 degrees.
- Object > Artboard > Fit to Artwork Bounds.

**Comment by drHyperion451** [comment]
This is very good. Thanks for the explanation. I will make the rest flags the same format.
I do not use ilustrator, I'm using inkscape, but I think I could replicate the steps as well

**Comment by drHyperion451** [comment]
https://inkscape.org/forums/beyond/flag-in-a-wind/

**Comment by drHyperion451** [comment]
Ignore this url. I've been working on the inkscape solution but needed to shutdown the PC 😂

**Pull request merged**
