### PR TITLE
Language Bar + Polish,French language

### PR DESCRIPTION
**Pull request by kbvivi**
Added some simple Language bar + polish translation of a website.

### CODE REVIEW

**Comment by kbvivi** [comment]
Merged french translation from #50 to this pull request.

**Comment by drHyperion451** [comment]
Thanks. I'm reviewing the PR and running it in Safari works perfectly and I love it. However in Firefox 121 doesn't show anything at all. I'm gonna try fix it myself but anything could help as well.

**Comment by drHyperion451** [comment]
Also I need to make the globe symbol dark theme friendly, but it's not priority

**Comment by jojoblackFr** [comment]
gonna check with firefox then

**Comment by drHyperion451** [comment]
Found the issue. Incrementing the boottom position of the menubar reveals the menubar is overflow and shows the globe very far down. Looking for the answer. Maybe it's related to the languages not being absolute/out of the flexbox?

**Comment by drHyperion451** [comment]
Yeah... It's the languages div whos causing the problem in firefox. Damn you Mozilla!! 😂

**Comment by jojoblackFr** [comment]
Opera got the same problem

and language button is clickable without being seen
image

**Comment by drHyperion451** [comment]
Found a quick solution to the position. I'm gonna try merge it and please test it

**Comment by jojoblackFr** [comment]
yeah everything got the placement issue, got it with chrome
image

**Comment by drHyperion451** [comment]
Tell me if it works now. I'm gonna fix the clickable issue as well

**Comment by jojoblackFr** [comment]
work on Opera, Firefox and Chrome

**Comment by drHyperion451** [comment]
Check this out

**Comment by jojoblackFr** [comment]
Opera + Firefox + Chrome passed flawlessly

**Comment by jojoblackFr** [comment]
gonna change logo color first

**Comment by jojoblackFr** [comment]
globe

**Comment by drHyperion451** [comment]
Don't worry. It's just a mistake inside the css. Im gona push the changes

**Comment by drHyperion451** [comment]
Check it out. If it works then I will merge soon

**Comment by drHyperion451** [comment]
Btw, how can I directly push from local changes to this pr? I've been doing this all inside github.com, but my workspace is local. Already tried something like

```sh
git fetch origin pull/51/head:lang_bar
git switch lang_bar

git add *; git commit -m "commit name"
git push origin lang_bar```

However, this creates a new lang_bar branch. How can I push to this speciffic pull request lol?

**Comment by jojoblackFr** [comment]
idk i can't push to this pr at all

**Comment by drHyperion451** [comment]
Maybe when I merge the branch I will do it

**Pull request merged**
