### PR TITLE
Button propperly added

### PR DESCRIPTION
**Pull request by drHyperion451**
@u-RraaLL Please review this change. Also I can't make it more easy because my subdomain is not whitelisted. See the issue #30  for more info.

### CODE REVIEW

**Comment by u-RraaLL** [comment]
> `forceOption = 'yes'`

Doesn't that make the website always say yes, without checking?

**Comment by drHyperion451** [comment]
> > `forceOption = 'yes'`
> 
> Doesn't that make the website always say yes, without checking?

Yes, before mergin i will delete this

**Comment by u-RraaLL** [comment]
Ok, give us some time to discuss how we want to implement this. At the very least, I'd like to put some instructions similar to what I've done in the pinned thread earlier.

**Comment by u-RraaLL** [comment]
Okay, I see two resolutions to this:

1. I make a dedicated wiki page on reddit with instructions to updating the list via a link and we link to that.
2. I add the instructions here, but we'd need to button to change links based on the age of the solution.
- https://ublockorigin.github.io/uAssets/update-lists.html?listkeys=ublock-quick-fixes&manual=1 if the solution is younger than 6hrs
- https://ublockorigin.github.io/uAssets/update-lists.html?listkeys=ublock-quick-fixes if it's older than 6hrs.
These will still lead to the "try again" page though.

While I wasn't told this directly, I think the chances for this project moving under uBO or it being "whitelisted" for updates are very slim.

So what do you think about these two options?

**Comment by drHyperion451** [comment]
> 2\. I add the instructions here, but we'd need to button to change links based on the age of the solution.

Not only this is pretty good to user experience but coincidentally I've created a function for the "updated since" that can be perfectly used on this solution. I like this.

**Comment by u-RraaLL** [comment]
I added the instructions. Please make the button behave this way:

1. The latest fix is under 10 minutes old - no button.
2. 10 minutes to 6 hours - the longer link.
3. Over 6 hours, the shorter link.

Once that's done we can probably go live with this.

**Comment by drHyperion451** [comment]
Had a problem with diverging branches. I'm adding your requests.

**Review by u-RraaLL — APPROVED** [review]
Looks good.

**Comment by drHyperion451** [comment]
Done. Got ip blocked for an hour trying but I think this is it. Check it out @u-RraaLL

**Review by u-RraaLL — APPROVED** [review]

**Pull request merged**
